### ISSUE TITLE
Passing parameters

### ISSUE THREAD

**Issue by prasanna32** [nilendrat/EfCoreMultipleResults#1]
This is not an issue. I wanted to know as how can I pass parameters to the stored procedures using ExecuteMultipleResults and parameters ?

**Comment by nilendrat** [comment]
I have updated the solution to add SQL parameters and with necessary classes , please refer **DataAccess.cs** to  see the example of how to pass parameters and needed return types.

**Comment by prasanna32** [comment]
Thank you!
